Paper less feature
Prescrypto/ErsteOps pull request #114
Opened 2022-05-24 20:26 UTC by vezino

The goal is to allow the contact doctor to capture the medical report

2022-08-19 21:54 UTC, xtornasol512 commented on ersteops/emergency/admin.py
> +admin.site.register(MedicalReport)
No se te olvide agregar saltos de línea al final de los archivos
Te recomiendo buscar algun plugin para tu IDE , para que lo haga automático cada que guardas el archivo

2022-08-19 21:55 UTC, xtornasol512 commented on ersteops/emergency/migrations/0015_auto_20220517_1937.py
> +            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='em_attention_hospital_name', to='emergency.AttentionHospital', verbose_name='hospital'),
Cuando se borre alguna llave foránea, o lo protegemos o le ponemos en cascada nO?
O cuál es la razón de dejarlo en DO_NOTHING? @vezino

2022-08-19 21:56 UTC, xtornasol512 commented on ersteops/emergency/migrations/0016_emergency_medical_report.py
> +            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_report', to='paperless.MedicalReport', verbose_name='Parte Medico'),
idem, about "on_delete"

2022-08-19 21:57 UTC, xtornasol512 commented on ersteops/emergency/views.py
> +                              body='Your Yummy Cupcakes Company order of 1 dozen frosted cupcakes has shipped and should be delivered on July 10, 2019. Details: {}'.format(msg_content),
Este mensaje va a quedar en el código? o en que momento lo remplazarás?

2022-08-19 21:58 UTC, xtornasol512 commented on ersteops/emergency/views.py
> +        logger.info('[ WHATSAPP MESSAGE SUCCESS ]')
Después que el QA termine, una buena práctica para que no se gaste tanto log, es quitar los mensajes en casos de exito, solo dejar los de error, que son los que si necesitamos debuggear

2022-08-19 21:58 UTC, xtornasol512 commented on ersteops/ersteops/settings.py
> +
Add EOF

2022-08-19 21:58 UTC, xtornasol512 commented on ersteops/paperless/dict_fields.py
> +}
Add EOF

2022-08-19 21:59 UTC, xtornasol512 commented on ersteops/paperless/forms.py
> +
Add EOF

2022-08-19 21:59 UTC, xtornasol512 commented on ersteops/paperless/forms.py
> +  pathological_history_arterial_hypertension = forms.ChoiceField(
MUY DENSO ESTE MODELO!

2022-08-19 22:00 UTC, xtornasol512 commented on ersteops/paperless/migrations/0005_medicalreport_user.py
> +            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
IDEM about on_delete

2022-08-19 22:00 UTC, xtornasol512 commented on ersteops/paperless/migrations/0006_auto_20220603_2337.py
> +            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
idem

2022-08-19 22:01 UTC, xtornasol512 commented on ersteops/printpdf/urls.py
> +    #url(r'^$', login_required(AddPetFileVisit.as_view(), login_url='/login/'), name="agregar consulta"),
Las URL comentadas se pueden quitar

2022-08-19 22:01 UTC, xtornasol512 commented on ersteops/printpdf/urls.py
> +]
add EOF

2022-08-19 22:02 UTC, xtornasol512 commented on ersteops/printpdf/views.py
> +# -*- coding: utf-8 -*-
Que version de python es esto?
En versiones 3.6 en adelante ya no es necesario tener ni el header de utf ni el 
`from __future__ import unicode_literals`

2022-08-19 22:04 UTC, xtornasol512 commented on ersteops/printpdf/views.py
> +def get_medical_report(pk):
Puff si que son muchos datos

Puedes darle más descripción  a la función porfa
Para que quede sentado que tratas la info y la serializas en json

2022-08-19 22:05 UTC, xtornasol512 commented on ersteops/printpdf/views.py
> +    png_recovered = base64.decodestring(res)
Al final si te decidiste en salvarlo base 64, lo único a tener en cuenta es el tamaño de los archivos, si es muy pesado se vuelve pessado tmb a la BD guardar y leer

Sabes el promedio de peso de esos archivos?

2022-08-19 22:06 UTC, xtornasol512 commented on ersteops/printpdf/views.py
> +  return ns
add EOF

2022-08-19 22:07 UTC, xtornasol512 commented on ersteops/static/maps/css/locatorplus.css
> +}
add EOF

2022-08-19 22:07 UTC, xtornasol512 commented on ersteops/static/maps/css/style.css
> +  }
add EOF

2022-08-19 22:07 UTC, xtornasol512 commented on ersteops/static/maps/js/locatorplus.js
> +          location.travelDistanceValue = travelDistanceValue;
Esta muy loco este codigo! Si es tuyo felicidades! Pero si no porfa agrega referencia de la librería

2022-08-19 22:07 UTC, xtornasol512 commented on ersteops/static/paperless/css/styles.css
> +}
add eof

2022-08-19 22:08 UTC, xtornasol512 commented on ersteops/templates/paperless/detail_medical_report.html
> +
Vientos, puedes agregar un screenshoot de como quedo la interfaz?

2022-08-19 22:08 UTC, xtornasol512 commented on ersteops/templates/paperless/list_active_medical_reports.html
> +  <script src="{% static "uikit-3.14.1/js/uikit.js" %}"></script>
Bien!

2022-08-19 22:09 UTC, xtornasol512 commented on frontend/components/MedicalReport/script.js
> +import 'filters/time-since';
Te quedo muy cool esto!

2022-08-19 22:09 UTC, xtornasol512 requested changes
Puff muy denso, pero si deje varios comments a revisar, checalos y despúes quedamos para subirlo!

2022-09-01 01:00 UTC, vezino commented on ersteops/printpdf/views.py
> +    png_recovered = base64.decodestring(res)
cada archivo de firma queda de  5 kb max y son 2 por parte medico, osea 10 kb, idealmente solo guardaremos el pdf en S3

2022-09-01 01:00 UTC, vezino commented on ersteops/printpdf/views.py
> +  return ns
done

2022-09-01 01:02 UTC, vezino commented on ersteops/static/maps/css/locatorplus.css
> +}
done

2022-09-01 01:02 UTC, vezino commented on ersteops/static/maps/css/style.css
> +  }
done

2022-09-01 01:07 UTC, vezino commented on ersteops/static/maps/js/locatorplus.js
> +          location.travelDistanceValue = travelDistanceValue;
creo esto salio de aqui: https://github.com/googlemaps/

2022-09-01 01:07 UTC, vezino commented on ersteops/static/paperless/css/styles.css
> +}
done

2022-09-01 01:10 UTC, vezino commented on ersteops/templates/paperless/detail_medical_report.html
> +
[screencapture-ersteops-heroku-20-herokuapp-paperless-new-11-2022-08-31-20_08_40.pdf](https://github.com/Prescrypto/ErsteOps/files/9466033/screencapture-ersteops-heroku-20-herokuapp-paperless-new-11-2022-08-31-20_08_40.pdf)
[screencapture-ersteops-heroku-20-herokuapp-paperless-new-11-2022-08-31-20_08_16.pdf](https://github.com/Prescrypto/ErsteOps/files/9466036/screencapture-ersteops-heroku-20-herokuapp-paperless-new-11-2022-08-31-20_08_16.pdf)

2022-09-01 01:12 UTC, vezino commented on frontend/components/MedicalReport/script.js
> +import 'filters/time-since';
andaba inspirado! ja

2022-09-06 02:37 UTC, xtornasol512 approved these changes
LGTM!

2022-09-06 02:37 UTC, merged